"""fix: align payment_invoices crypto_bot_invoice_id constraint with model

Revision ID: 0c7e1efbbe2a
Revises: c3d4e5f6a7b8
Create Date: 2026-02-14 17:13:52.499876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7e1efbbe2a'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_invoices_crypto_bot_invoice_id_key', 'payment_invoices', type_='unique')
    op.create_index(op.f('ix_payment_invoices_crypto_bot_invoice_id'), 'payment_invoices', ['crypto_bot_invoice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_invoices_crypto_bot_invoice_id'), table_name='payment_invoices')
    op.create_unique_constraint('payment_invoices_crypto_bot_invoice_id_key', 'payment_invoices', ['crypto_bot_invoice_id'])
    # ### end Alembic commands ###
