"""add_last_notified_at

Revision ID: 9b7accc62b32
Revises: 1b7603ea6473
Create Date: 2026-02-09 11:20:33.664055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7accc62b32'
down_revision: Union[str, None] = '1b7603ea6473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_notified_at')
    # ### end Alembic commands ###
