"""Initial schema

Revision ID: cc06b4d0db70
Revises: 
Create Date: 2026-02-06 18:30:03.495082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc06b4d0db70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('completed_orders_count', sa.Integer(), nullable=False),
    sa.Column('active_orders_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('subscribed_categories', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('subscribed_cities', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('notification_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('balance_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('RECHARGE', 'ORDER_TAKE', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_transactions_created_at'), 'balance_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_balance_transactions_type'), 'balance_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_balance_transactions_user_id'), 'balance_transactions', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DELETED', 'CLOSED_NO_RESPONSE', 'COMPLETED', name='orderstatus'), nullable=False),
    sa.Column('city_locked', sa.Boolean(), nullable=False),
    sa.Column('expires_in_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('customer_responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_category'), 'orders', ['category'], unique=False)
    op.create_index(op.f('ix_orders_city'), 'orders', ['city'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('client_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('executor_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'client_id', name='uq_client_review_per_order')
    )
    op.create_index(op.f('ix_client_reviews_client_id'), 'client_reviews', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_reviews_created_at'), 'client_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_client_reviews_executor_id'), 'client_reviews', ['executor_id'], unique=False)
    op.create_index(op.f('ix_client_reviews_order_id'), 'client_reviews', ['order_id'], unique=False)
    op.create_table('executor_complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('executor_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('complaint', sa.Enum('NO_RESPONSE', 'CANCELLED_ORDER', 'INADEQUATE_BEHAVIOR', 'FALSE_INFO', 'OTHER', name='complaintreason'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'executor_id', name='uq_executor_complaint_per_order')
    )
    op.create_index(op.f('ix_executor_complaints_client_id'), 'executor_complaints', ['client_id'], unique=False)
    op.create_index(op.f('ix_executor_complaints_created_at'), 'executor_complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_executor_complaints_executor_id'), 'executor_complaints', ['executor_id'], unique=False)
    op.create_index(op.f('ix_executor_complaints_order_id'), 'executor_complaints', ['order_id'], unique=False)
    op.create_table('executor_takes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('executor_id', sa.BigInteger(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'executor_id', name='uq_executor_take_per_order')
    )
    op.create_index(op.f('ix_executor_takes_executor_id'), 'executor_takes', ['executor_id'], unique=False)
    op.create_index(op.f('ix_executor_takes_order_id'), 'executor_takes', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executor_takes_order_id'), table_name='executor_takes')
    op.drop_index(op.f('ix_executor_takes_executor_id'), table_name='executor_takes')
    op.drop_table('executor_takes')
    op.drop_index(op.f('ix_executor_complaints_order_id'), table_name='executor_complaints')
    op.drop_index(op.f('ix_executor_complaints_executor_id'), table_name='executor_complaints')
    op.drop_index(op.f('ix_executor_complaints_created_at'), table_name='executor_complaints')
    op.drop_index(op.f('ix_executor_complaints_client_id'), table_name='executor_complaints')
    op.drop_table('executor_complaints')
    op.drop_index(op.f('ix_client_reviews_order_id'), table_name='client_reviews')
    op.drop_index(op.f('ix_client_reviews_executor_id'), table_name='client_reviews')
    op.drop_index(op.f('ix_client_reviews_created_at'), table_name='client_reviews')
    op.drop_index(op.f('ix_client_reviews_client_id'), table_name='client_reviews')
    op.drop_table('client_reviews')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_city'), table_name='orders')
    op.drop_index(op.f('ix_orders_category'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_balance_transactions_user_id'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_type'), table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_created_at'), table_name='balance_transactions')
    op.drop_table('balance_transactions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
