"""update_client_review_unique_constraint

Revision ID: e08bf67ee445
Revises: cc06b4d0db70
Create Date: 2026-02-06 19:41:45.470669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08bf67ee445'
down_revision: Union[str, None] = 'cc06b4d0db70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_review_per_order', 'client_reviews', type_='unique')
    op.create_unique_constraint('uq_client_review_per_order', 'client_reviews', ['order_id', 'client_id', 'executor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_review_per_order', 'client_reviews', type_='unique')
    op.create_unique_constraint('uq_client_review_per_order', 'client_reviews', ['order_id', 'client_id'])
    # ### end Alembic commands ###
